classdef DataTab
    %DATATAB  Builds the Data ribbon tab.
    %
    %   Groups:
    %     Flight    : Import Wizard / Load Flight 1 / Load Flight 2
    %     Video     : Load Video 1 / Load Video 2 / Clear Video
    %     Reference : Load Coastline
    %     Validate  : Validate / Est. FPS / Summary

    methods (Static)
        function tab = build()
            Btn = @flightdash.studio.ribbon.RibbonButton;
            Grp = @flightdash.studio.ribbon.RibbonGroup;

            flight = Grp('Flight', { ...
                Btn('Wizard',   'Data:ImportWizard', ...
                    'Tooltip', 'Import flight data with the mapping wizard'), ...
                Btn('Flight 1', 'Data:LoadFlight1', ...
                    'Tooltip', 'Load CSV for flight 1'), ...
                Btn('Flight 2', 'Data:LoadFlight2', ...
                    'Tooltip', 'Load CSV for flight 2')});

            video = Grp('Video', { ...
                Btn('Video 1', 'Video:LoadVideo1', ...
                    'Tooltip', 'Load video for flight 1'), ...
                Btn('Video 2', 'Video:LoadVideo2', ...
                    'Tooltip', 'Load video for flight 2'), ...
                Btn('Clear',   'Video:Clear', ...
                    'Tooltip', 'Clear loaded videos')});

            ref = Grp('Reference', { ...
                Btn('Coast', 'Data:LoadCoast', ...
                    'Tooltip', 'Load coastline overlay data')});

            validate = Grp('Validate', { ...
                Btn('Validate', 'Data:Validate', ...
                    'Tooltip', 'Run data validation checks'), ...
                Btn('Est FPS',  'Data:EstimateFps', ...
                    'Tooltip', 'Estimate flight data FPS'), ...
                Btn('Summary',  'Data:Summary', ...
                    'Tooltip', 'Show data summary report')});

            tab = flightdash.studio.ribbon.RibbonTab('Data', ...
                {flight, video, ref, validate});
        end
    end
end
