classdef HomeTab
    %HOMETAB  Builds the Home ribbon tab.
    %
    %   Groups:
    %     Project : New / Open / Save  (each with dropdown)
    %     Session : + Session (dropdown)
    %     History : Undo / Redo
    %     Layout  : Explorer toggle / Right dock toggle / Theme toggle

    methods (Static)
        function tab = build()
            Btn = @flightdash.studio.ribbon.RibbonButton;
            Grp = @flightdash.studio.ribbon.RibbonGroup;

            project = Grp('Project', { ...
                Btn('New',  'File:NewProject', ...
                    'Tooltip', 'Create a new project', ...
                    'HasDropdown', true, ...
                    'DropdownItems', {{'New Project','File:NewProject'}, ...
                                      {'New Comparison Graph','Plot:NewComparison'}}), ...
                Btn('Open', 'File:OpenProject', ...
                    'Tooltip', 'Open an existing .frsproj project', ...
                    'HasDropdown', true, ...
                    'DropdownItems', {{'Open Project...','File:OpenProject'}, ...
                                      {'Open Sample Project','Studio:OpenSampleProject'}}), ...
                Btn('Save', 'File:SaveProject', ...
                    'Tooltip', 'Save the current project', ...
                    'HasDropdown', true, ...
                    'DropdownItems', {{'Save','File:SaveProject'}, ...
                                      {'Save Project As...','File:SaveProjectAs'}, ...
                                      {'Import Session Config','File:ImportSession'}, ...
                                      {'Export Session Config','File:ExportSession'}})});

            session = Grp('Session', { ...
                Btn('+ Sess', 'Project:AddSession', ...
                    'Tooltip', 'Add a new review session', ...
                    'HasDropdown', true, ...
                    'DropdownItems', {{'Add Review Session','Project:AddSession'}, ...
                                      {'Duplicate Session','Project:DuplicateSession'}, ...
                                      {'Rename Session','Project:RenameSession'}, ...
                                      {'Delete Session','Project:DeleteSession'}})});

            history = Grp('History', { ...
                Btn('Undo', 'Edit:Undo', 'Tooltip', 'Undo last change'), ...
                Btn('Redo', 'Edit:Redo', 'Tooltip', 'Redo last undone change')});

            layout = Grp('Layout', { ...
                Btn('Explorer', 'Toolbar:ToggleExplorer', ...
                    'Tooltip', 'Show/hide the project explorer pane'), ...
                Btn('Dock',     'Toolbar:ToggleRightDock', ...
                    'Tooltip', 'Show/hide the right dock pane'), ...
                Btn('Theme',    'Pref:Theme:Toggle', ...
                    'Tooltip', 'Toggle light/dark theme')});

            tab = flightdash.studio.ribbon.RibbonTab('Home', ...
                {project, session, history, layout});
        end
    end
end
