classdef PlaybackTab
    %PLAYBACKTAB  Builds the Playback ribbon tab.
    %
    %   Groups:
    %     Playback : Play / Stop / Prev / Next  (symbol icons)
    %     Frame    : Snapshot / Decode Settings / Metadata

    methods (Static)
        function tab = build()
            Btn = @flightdash.studio.ribbon.RibbonButton;
            Grp = @flightdash.studio.ribbon.RibbonGroup;

            play = Grp('Playback', { ...
                Btn('Play', 'Toolbar:Play', 'Tooltip', 'Start playback'), ...
                Btn('Stop', 'Toolbar:Stop', 'Tooltip', 'Stop playback'), ...
                Btn('Prev', 'Toolbar:Prev', 'Tooltip', 'Previous frame'), ...
                Btn('Next', 'Toolbar:Next', 'Tooltip', 'Next frame')});

            frame = Grp('Frame', { ...
                Btn('Snap',     'Video:Snapshot', ...
                    'Tooltip', 'Snapshot current frame'), ...
                Btn('Decode',   'Video:DecodeSettings', ...
                    'Tooltip', 'Video decode settings'), ...
                Btn('Metadata', 'Video:Metadata', ...
                    'Tooltip', 'Show video metadata')});

            tab = flightdash.studio.ribbon.RibbonTab('Playback', {play, frame});
        end
    end
end
