classdef PlotTab
    %PLOTTAB  Builds the Plot ribbon tab.
    %
    %   Groups:
    %     Plot    : New Graph / New Comparison / Add Selected
    %     Details : Details / Axis / Link Axes
    %     Export  : Export Figure / Copy Figure
    %     Window  : Tile H / Tile V / Cascade / Close All ▼

    methods (Static)
        function tab = build()
            Btn = @flightdash.studio.ribbon.RibbonButton;
            Grp = @flightdash.studio.ribbon.RibbonGroup;

            plot = Grp('Plot', { ...
                Btn('New',     'Plot:NewGraph',      'Tooltip', 'Create a new graph'), ...
                Btn('Compare', 'Plot:NewComparison', 'Tooltip', 'New comparison graph'), ...
                Btn('Add',     'Plot:AddSelected',   'Tooltip', 'Add selected variable to current graph')});

            details = Grp('Details', { ...
                Btn('Details', 'Plot:Details',  'Tooltip', 'Plot details panel'), ...
                Btn('Axis',    'Plot:Axis',     'Tooltip', 'Axis settings'), ...
                Btn('Link',    'Plot:LinkAxes', 'Tooltip', 'Link plot axes')});

            export = Grp('Export', { ...
                Btn('Export', 'Plot:Export', 'Tooltip', 'Export current figure'), ...
                Btn('Copy',   'Plot:Copy',   'Tooltip', 'Copy figure to clipboard')});

            window = Grp('Window', { ...
                Btn('Tile H',  'Window:TileH', 'Tooltip', 'Tile windows horizontally'), ...
                Btn('Tile V',  'Window:TileV', 'Tooltip', 'Tile windows vertically'), ...
                Btn('Cascade', 'Window:Cascade', 'Tooltip', 'Cascade windows'), ...
                Btn('Close',   'Window:CloseAll', ...
                    'Tooltip', 'Close all tabs', ...
                    'HasDropdown', true, ...
                    'DropdownItems', {{'Close All Tabs','Window:CloseAll'}, ...
                                      {'Show Object Manager','Window:ShowObjectMgr'}, ...
                                      {'Show Logs','Window:ShowLogs'}})});

            tab = flightdash.studio.ribbon.RibbonTab('Plot', ...
                {plot, details, export, window});
        end
    end
end
