classdef ReviewTab
    %REVIEWTAB  Builds the Review ribbon tab.
    %
    %   Groups:
    %     Markers : + ROI / + Marker
    %     Analyze : Analyze ▼ / Recalc
    %     Filter  : Filter ▼ / FFT
    %     Report  : Compare / Export Table / Generate Report

    methods (Static)
        function tab = build()
            Btn = @flightdash.studio.ribbon.RibbonButton;
            Grp = @flightdash.studio.ribbon.RibbonGroup;

            markers = Grp('Markers', { ...
                Btn('+ ROI',  'Review:AddRoi', 'Tooltip', 'Add an ROI to the active plot'), ...
                Btn('+ Mark', 'Review:AddEvent', 'Tooltip', 'Add an event marker')});

            analyze = Grp('Analyze', { ...
                Btn('Analyze', 'Toolbar:Analyze', ...
                    'Tooltip', 'Run analysis on the active selection', ...
                    'HasDropdown', true, ...
                    'DropdownItems', {{'ROI Statistics','Analysis:RoiStats'}, ...
                                      {'Event Detection','Analysis:EventDetect'}, ...
                                      {'Sync Quality Analysis','Analysis:SyncQuality'}, ...
                                      {'Compare Sessions','Analysis:Compare'}}), ...
                Btn('Recalc', 'Toolbar:Recalc', 'Tooltip', 'Recalculate current analysis')});

            filt = Grp('Filter', { ...
                Btn('Filter', 'Analysis:Filter', ...
                    'Tooltip', 'Apply signal filtering', ...
                    'HasDropdown', true, ...
                    'DropdownItems', {{'Signal Filtering','Analysis:Filter'}, ...
                                      {'Smoothing','Analysis:Smooth'}}), ...
                Btn('FFT', 'Analysis:FFT', 'Tooltip', 'Run FFT analysis')});

            report = Grp('Report', { ...
                Btn('Compare', 'Review:Compare', 'Tooltip', 'Compare sessions'), ...
                Btn('Export',  'Review:ExportTable', 'Tooltip', 'Export review table'), ...
                Btn('Report',  'Review:Report', 'Tooltip', 'Generate review report')});

            tab = flightdash.studio.ribbon.RibbonTab('Review', ...
                {markers, analyze, filt, report});
        end
    end
end
