classdef SyncTab
    %SYNCTAB  Builds the Sync ribbon tab (Sync + Quality groups).

    methods (Static)
        function tab = build()
            Btn = @flightdash.studio.ribbon.RibbonButton;
            Grp = @flightdash.studio.ribbon.RibbonGroup;

            sync = Grp('Sync', { ...
                Btn('Flight',   'Sync:Flight', ...
                    'Tooltip', 'Flight time synchronization'), ...
                Btn('Video',    'Sync:VideoData', ...
                    'Tooltip', 'Video <-> flight data synchronization'), ...
                Btn('SyncTime', 'Toolbar:SyncTime', ...
                    'Tooltip', 'Sync time tools', ...
                    'HasDropdown', true, ...
                    'DropdownItems', {{'Reset Video Sync','Sync:ResetVideo'}, ...
                                      {'Sync Offset Editor','Sync:OffsetEditor'}})});

            quality = Grp('Quality', { ...
                Btn('Check', 'Sync:QualityCheck', ...
                    'Tooltip', 'Sync quality check')});

            tab = flightdash.studio.ribbon.RibbonTab('Sync', {sync, quality});
        end
    end
end
