classdef HeaderBar
    % flightdash.view.HeaderBar
    % - 최상단 헤더 (파일 선택 버튼 3개 + Debug 체크박스 + 비행시간 동기 입력/버튼)
    % - 콜백은 메인 메서드 직접 참조 (점진 마이그레이션, FileController로 이전 가능)
    
    methods (Static)
        function ui = build(mainLayout)
            % [REFACTOR] app 의존 제거 - 콜백은 EventBus.publish로 발행
            import flightdash.util.EventBus
            import flightdash.util.AppEventData
            ui = struct();
            UIScale = flightdash.util.UIScale;   % High-DPI 폭 보정
            hHeaderPanel = uipanel(mainLayout, 'BackgroundColor', 'w', 'BorderType', 'none');
            glHeader = uigridlayout(hHeaderPanel, [1 7]);
            glHeader.ColumnWidth = { ...
                UIScale.px(140), UIScale.px(140), UIScale.px(140), ...
                '1x', UIScale.px(80), UIScale.px(150), UIScale.px(150)};
            glHeader.RowHeight = {'fit'};
            glHeader.Padding = [5 5 5 5];
            glHeader.ColumnSpacing = 5;
            
            uibutton(glHeader, 'Text', '비행경로 1 선택', ...
                'BackgroundColor', [0.15 0.38 0.82], 'FontColor', 'w', ...
                'FontSize', 13, 'FontWeight', 'bold', ...
                'ButtonPushedFcn', @(~,~) EventBus.publish('FlightFileRequested', AppEventData(1)));
            uibutton(glHeader, 'Text', '비행경로 2 선택', ...
                'BackgroundColor', [0.31 0.27 0.90], 'FontColor', 'w', ...
                'FontSize', 13, 'FontWeight', 'bold', ...
                'ButtonPushedFcn', @(~,~) EventBus.publish('FlightFileRequested', AppEventData(2)));
            uibutton(glHeader, 'Text', '해안선 정보', ...
                'BackgroundColor', [0.06 0.65 0.50], 'FontColor', 'w', ...
                'FontSize', 13, 'FontWeight', 'bold', ...
                'ButtonPushedFcn', @(~,~) EventBus.publish('CoastFileRequested', AppEventData()));
            uilabel(glHeader, 'Text', '');
            
            uicheckbox(glHeader, 'Text', 'Debug', 'Value', false, ...
                'FontSize', 12, 'FontWeight', 'bold', ...
                'Tooltip', 'XLim 변경, 캐시 변동 등 디버그 로그를 콘솔에 출력', ...
                'ValueChangedFcn', @(src,~) EventBus.publish('DebugModeToggled', AppEventData(0, src.Value)));
            
            ui.SyncInput = uieditfield(glHeader, 'text', 'Value', '', ...
                'Tooltip', 'ex: 23.4, 34.4', 'FontSize', 13);
            ui.SyncBtn = uibutton(glHeader, 'Text', '비행시간 동기', ...
                'BackgroundColor', [0.58 0.0 0.83], 'FontColor', 'w', ...
                'FontSize', 13, 'FontWeight', 'bold', ...
                'ButtonPushedFcn', @(~,~) EventBus.publish('SyncToggled', AppEventData()));
        end
    end
end
