classdef HeaderBar
    % flightdash.view.HeaderBar
    % Top header: file buttons, debug toggle, window controls, and sync controls.

    methods (Static)
        function ui = build(mainLayout)
            ui = struct();
            UIScale = flightdash.util.UIScale;

            ui.HeaderPanel = uipanel(mainLayout, ...
                'BackgroundColor', 'w', 'BorderType', 'none');
            ui.HeaderGrid = uigridlayout(ui.HeaderPanel, [1 11]);
            ui.HeaderGrid.ColumnWidth = { ...
                UIScale.px(96), UIScale.px(96), UIScale.px(80), ...
                UIScale.px(96), UIScale.px(96), UIScale.px(92), '1x', UIScale.px(42), ...
                UIScale.px(76), UIScale.px(120), UIScale.px(120)};
            ui.HeaderGrid.RowHeight = {'fit'};
            ui.HeaderGrid.Padding = [5 5 5 5];
            ui.HeaderGrid.ColumnSpacing = 5;
            ui.HeaderGrid.RowSpacing = 3;

            ui.Flight1Button = uibutton(ui.HeaderGrid, 'Text', 'Flight 1', ...
                'BackgroundColor', [0.15 0.38 0.82], 'FontColor', 'w', ...
                'FontSize', 13, 'FontWeight', 'bold', ...
                'ButtonPushedFcn', @(~,~) flightdash.util.EventBus.publish( ...
                    'FlightFileRequested', flightdash.util.AppEventData(1)));
            ui.Flight2Button = uibutton(ui.HeaderGrid, 'Text', 'Flight 2', ...
                'BackgroundColor', [0.31 0.27 0.90], 'FontColor', 'w', ...
                'FontSize', 13, 'FontWeight', 'bold', ...
                'ButtonPushedFcn', @(~,~) flightdash.util.EventBus.publish( ...
                    'FlightFileRequested', flightdash.util.AppEventData(2)));
            ui.CoastButton = uibutton(ui.HeaderGrid, 'Text', 'Coast', ...
                'BackgroundColor', [0.06 0.65 0.50], 'FontColor', 'w', ...
                'FontSize', 13, 'FontWeight', 'bold', ...
                'ButtonPushedFcn', @(~,~) flightdash.util.EventBus.publish( ...
                    'CoastFileRequested', flightdash.util.AppEventData()));

            ui.ExportConfigButton = uibutton(ui.HeaderGrid, 'Text', 'Export CFG', ...
                'Tooltip', 'Export the current session configuration', ...
                'FontSize', 12, 'FontWeight', 'bold', ...
                'ButtonPushedFcn', @(~,~) flightdash.util.EventBus.publish( ...
                    'ConfigExportRequested', flightdash.util.AppEventData()));

            ui.ImportConfigButton = uibutton(ui.HeaderGrid, 'Text', 'Import CFG', ...
                'Tooltip', 'Import a saved session configuration', ...
                'FontSize', 12, 'FontWeight', 'bold', ...
                'ButtonPushedFcn', @(~,~) flightdash.util.EventBus.publish( ...
                    'ConfigImportRequested', flightdash.util.AppEventData()));

            ui.ChannelViewDropDown = uidropdown(ui.HeaderGrid, ...
                'Items', {'Both', 'Flight 1', 'Flight 2'}, ...
                'ItemsData', {'both', 'flight1', 'flight2'}, ...
                'Value', 'both', ...
                'Tooltip', 'Show both flights or focus one flight', ...
                'ValueChangedFcn', @(src,~) flightdash.util.EventBus.publish( ...
                    'ChannelViewChanged', flightdash.util.AppEventData(0, src.Value)));

            ui.HeaderSpacer = uilabel(ui.HeaderGrid, 'Text', '');

            ui.FitScreenButton = uibutton(ui.HeaderGrid, 'Text', 'Max', ...
                'Tooltip', 'Maximize / restore', ...
                'FontSize', 12, 'FontWeight', 'bold', ...
                'ButtonPushedFcn', @(~,~) flightdash.util.EventBus.publish( ...
                    'LayoutFitRequested', flightdash.util.AppEventData()));

            ui.DebugBox = uicheckbox(ui.HeaderGrid, 'Text', 'Debug', 'Value', false, ...
                'FontSize', 12, 'FontWeight', 'bold', ...
                'Tooltip', 'Print debug logs to the MATLAB console', ...
                'ValueChangedFcn', @(src,~) flightdash.util.EventBus.publish( ...
                    'DebugModeToggled', flightdash.util.AppEventData(0, src.Value)));

            ui.SyncInput = uieditfield(ui.HeaderGrid, 'text', 'Value', '', ...
                'Tooltip', 'ex: 23.4, 34.4', 'FontSize', 13);
            ui.SyncBtn = uibutton(ui.HeaderGrid, 'Text', 'Sync Time', ...
                'BackgroundColor', [0.58 0.0 0.83], 'FontColor', 'w', ...
                'FontSize', 13, 'FontWeight', 'bold', ...
                'ButtonPushedFcn', @(~,~) flightdash.util.EventBus.publish( ...
                    'SyncToggled', flightdash.util.AppEventData()));
        end
    end
end
