classdef AboutDialog
    %ABOUTDIALOG  Help > About Flight Review Studio (Phase B-1).
    %
    %   Tiny modal uifigure showing product / version / build / runtime /
    %   license placeholder / support. Content sourced from
    %   flightdash.util.VersionInfo.current().

    methods (Static)
        function show(parentApp)
            try
                UIScale = flightdash.util.UIScale;
                fig = uifigure( ...
                    'Name', 'About Flight Review Studio', ...
                    'Position', [200 200 UIScale.px(480) UIScale.px(280)], ...
                    'Resize', 'off');
                try
                    if nargin >= 1 && ~isempty(parentApp) && isvalid(parentApp) ...
                            && isprop(parentApp, 'CurrentThemeStruct') ...
                            && isstruct(parentApp.CurrentThemeStruct) ...
                            && isfield(parentApp.CurrentThemeStruct, 'Background')
                        fig.Color = parentApp.CurrentThemeStruct.Background;
                    end
                catch
                end

                grid = uigridlayout(fig, [3 1], ...
                    'RowHeight', {UIScale.px(32), '1x', UIScale.px(32)}, ...
                    'RowSpacing', 6, 'Padding', [12 12 12 12]);

                uilabel(grid, ...
                    'Text', 'Flight Review Studio', ...
                    'FontSize', 16, 'FontWeight', 'bold');

                bodyLabel = uilabel(grid, ...
                    'Text', flightdash.util.VersionInfo.aboutText(), ...
                    'FontSize', 11, ...
                    'VerticalAlignment', 'top', ...
                    'WordWrap', 'on');
                bodyLabel.Layout.Row = 2;

                btnRow = uigridlayout(grid, [1 2], ...
                    'ColumnWidth', {'1x', UIScale.px(96)}, ...
                    'ColumnSpacing', 6, 'Padding', [0 0 0 0]);
                btnRow.Layout.Row = 3;
                uilabel(btnRow, 'Text', '');
                uibutton(btnRow, 'Text', 'Close', ...
                    'ButtonPushedFcn', @(~,~) delete(fig));
            catch ME
                try, warning('AboutDialog:show', '%s', ME.message); catch, end
            end
        end
    end
end
