classdef LicenseDialog
    %LICENSEDIALOG  Help > License (Phase B-3) — placeholder UI only.
    %
    %   No real license verification. Future work: read license.json
    %   under prefdir, verify signature, etc.

    methods (Static)
        function show(parentApp)
            try
                UIScale = flightdash.util.UIScale;
                fig = uifigure( ...
                    'Name', 'License — Flight Review Studio', ...
                    'Position', [220 220 UIScale.px(440) UIScale.px(260)], ...
                    'Resize', 'off');
                try
                    if nargin >= 1 && ~isempty(parentApp) && isvalid(parentApp) ...
                            && isprop(parentApp, 'CurrentThemeStruct') ...
                            && isstruct(parentApp.CurrentThemeStruct) ...
                            && isfield(parentApp.CurrentThemeStruct, 'Background')
                        fig.Color = parentApp.CurrentThemeStruct.Background;
                    end
                catch
                end

                grid = uigridlayout(fig, [2 1], ...
                    'RowHeight', {'1x', UIScale.px(32)}, ...
                    'RowSpacing', 6, 'Padding', [12 12 12 12]);

                vi = flightdash.util.VersionInfo.current();
                body = sprintf([ ...
                    'License type:   Trial (placeholder)\n' ...
                    'Licensed to:    -\n' ...
                    'Expiration:     -\n' ...
                    'Activation:     Not implemented\n\n' ...
                    'Product:        %s\n' ...
                    'Version:        %s\n' ...
                    'Support:        %s\n\n' ...
                    'This dialog is a placeholder for future paid-distribution\n' ...
                    'workflows. No license verification is currently performed.'], ...
                    vi.ProductName, vi.Version, vi.SupportEmail);
                uilabel(grid, 'Text', body, 'FontSize', 11, ...
                    'VerticalAlignment', 'top', 'WordWrap', 'on');

                btnRow = uigridlayout(grid, [1 2], ...
                    'ColumnWidth', {'1x', UIScale.px(96)}, ...
                    'ColumnSpacing', 6, 'Padding', [0 0 0 0]);
                btnRow.Layout.Row = 2;
                uilabel(btnRow, 'Text', '');
                uibutton(btnRow, 'Text', 'Close', ...
                    'ButtonPushedFcn', @(~,~) delete(fig));
            catch ME
                try, warning('LicenseDialog:show', '%s', ME.message); catch, end
            end
        end
    end
end
