classdef VideoSessionState < handle
    %VIDEOSESSIONSTATE  Per-app video + sync state scaffold (R2 prep).
    %
    %   Holds the fields currently mirrored on the app as VideoState and
    %   VideoSyncState. R1 declares the shape; no app state has moved.
    %   R2 will populate this from the existing app properties and the
    %   app retains compatibility wrappers.
    %
    %   Owner: DashboardStateStore.

    properties (Access = public)
        % R8 storage. The legacy app properties are Dependent forwards
        % (declared on FlightDataDashboard) so subscript-assign
        % patterns like app.VideoState(fIdx).videoReader = X keep
        % working through MATLAB's get-modify-set chain.
        VideoState      struct = struct('videoReader',     {[], []}, ...
                                        'videoStartTime',  {0,  0}, ...
                                        'vidImageHandle',  {[], []})
        VideoSyncState  struct = struct('IsSynced',     {false, false}, ...
                                        'AnchorFrame',  {0,     0}, ...
                                        'AnchorOffset', {0,     0}, ...
                                        'AnchorTime',   {0,     0}, ...
                                        'VideoFps',     {70,    70}, ...
                                        'DataFps',      {50,    50}, ...
                                        'TotalFrames',  {0,     0}, ...
                                        'CurrentFrame', {1,     1})
        SyncState       struct = struct('IsSynced', false, ...
                                        'SyncT1', 0, ...
                                        'SyncT2', 0)
    end

    methods
        function obj = VideoSessionState()
        end
    end
end
